CREATE TABLE IF NOT EXISTS gift_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sender_name TEXT NOT NULL,
  sender_email TEXT,
  sender_phone TEXT NOT NULL,
  recipient_name TEXT NOT NULL,
  message TEXT,
  status TEXT DEFAULT 'pending'
);

-- Enable RLS
ALTER TABLE gift_requests ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (for the frontend form)
CREATE POLICY "Allow anonymous inserts on gift_requests"
  ON gift_requests
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Allow all operations for authenticated users (admin)
CREATE POLICY "Allow all operations for authenticated users on gift_requests"
  ON gift_requests
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
  
-- Also allow anon to select/update/delete for now since admin might be using anon key
CREATE POLICY "Allow anon select on gift_requests"
  ON gift_requests
  FOR SELECT
  TO anon
  USING (true);
  
CREATE POLICY "Allow anon update on gift_requests"
  ON gift_requests
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);
  
CREATE POLICY "Allow anon delete on gift_requests"
  ON gift_requests
  FOR DELETE
  TO anon
  USING (true);
